#!/bin/bash

echo "=== GitHub Repository Setup ==="
echo "Repository: https://github.com/pliekhus77/pr-suit-for-kiro.git"
echo ""
echo "To push to GitHub, you need to authenticate. Choose one option:"
echo ""
echo "Option 1: Personal Access Token (Recommended)"
echo "1. Go to GitHub.com → Settings → Developer settings → Personal access tokens → Tokens (classic)"
echo "2. Generate new token with 'repo' scope"
echo "3. Run: git remote set-url origin https://YOUR_TOKEN@github.com/pliekhus77/pr-suit-for-kiro.git"
echo "4. Run: git push -u origin main --force"
echo ""
echo "Option 2: SSH Key"
echo "1. Generate SSH key: ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "2. Add to GitHub: Settings → SSH and GPG keys → New SSH key"
echo "3. Run: git remote set-url origin git@github.com:pliekhus77/pr-suit-for-kiro.git"
echo "4. Run: git push -u origin main --force"
echo ""
echo "Option 3: GitHub CLI (if installed)"
echo "1. Run: gh auth login"
echo "2. Run: git push -u origin main --force"
echo ""
echo "Current status:"
git status
echo ""
echo "Current remote:"
git remote -v
echo ""
echo "Note: Using --force will override the existing README.md in the repository"
